export const KOM_TOKEN_IMAGE = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const KOM_WELCOME_IMAGE = 'https://ipfs.io/ipfs/QmYDLxg239npGJesRJzP6fqcokSyPJkorCaEm748HDKLTf';
export const STAKING_LP_BANNER_IMAGE = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const STAKING_V3_BANNER_IMAGE = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const STAKING_V1_BANNER_IMAGE = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const STAKING_V2_BANNER_IMAGE = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const STAKERSHIP_TRANSFERRED_IMAGE = 'https://ipfs.io/ipfs/QmdgCYcsueWf7Z5ejXsuTF7TDuXcgbvtSn2nr41w2dU9Qt'; // done
export const STAKERSHIP_RECEIVED_IMAGE = 'https://ipfs.io/ipfs/QmSZpPs8Bre2MZXfaFAQjYKHAxTpFRAawoHbHHkMdbhQKL'; //done
export const COMPOUND_MODE_CHANGED_IMAGED = 'https://ipfs.io/ipfs/QmWiojTGX1Dm6K7vdj8Cm5qFuHTMWhBUDe4eFqWgNC2Xai';
export const STAKING_V3_SUCCESS_IMAGE = 'https://ipfs.io/ipfs/QmNZyvWByRbKPKLWauEZdqD8L6pFomB3C7BeiBgrE7u5JW'; // done
export const STAKING_LP_SUCCESS_IMAGE = 'https://ipfs.io/ipfs/QmNZyvWByRbKPKLWauEZdqD8L6pFomB3C7BeiBgrE7u5JW'; // done
export const UNSTAKING_V3_SUCCESS_IMAGE = 'https://ipfs.io/ipfs/QmbD9fRUb7oULqBKwz3yKHkyRD3G8ZCiaDtVZ8b71XXFh8'; //done
